server.port=8200

#database configuraiton
spring.datasource.url=jdbc:mysql://localhost:3307/Food_Service_DB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password={cipher}28394af7ff69c36202b018638c0b5db1e6470caca7bebdcd744e7ac7060bb4d1

#jpa configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#actuator/info configuraiton
info.app.name=Food-Service-Development
info.app.description=This is Food Service in Development and configurations occur from config Server -->Github
info.app.version={cipher}f76d8d3870252fde69dd40a60612e99b092d94587ea7fe835d01de662b3fb1533a3f238a553abe01ba06f50c0d5cfd8f


